/* This file was automatically generated on Tue 29 Sep 2026 10:59:15 BST from
 * source: /scratch/djp75990/code/I11/bl11i-builder/etc/makeIocs/BL11I-EA-IOC-12.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

