# These are the IOCs we should create. The IOC should either have the same name
# as an xml or py file in etc/makeIocs, or be suffixed with _sim to create a
# simulation from that same file

# These are R3.14.11 IOCs 
ifneq (,$(findstring R3.14.11, $(EPICS_BASE))) 
#    IOCS += BL11I-EA-IOC-02 
endif

# These are R3.14.12.3 IOCs 
ifneq (,$(findstring R3.14.12.3, $(EPICS_BASE))) 
    IOCS += BL11I-CS-IOC-01 BL11I-CS-IOC-02 BL11I-CS-IOC-03 BL11I-CS-IOC-04 BL11I-CS-IOC-05 BL11I-CS-IOC-06 BL11I-CS-IOC-07 BL11I-CS-IOC-08 BL11I-CS-IOC-09
    IOCS += BL11I-DI-IOC-01 BL11I-DI-IOC-02 BL11I-DI-IOC-03
    IOCS += BL11I-EA-IOC-01 BL11I-EA-IOC-02 BL11I-EA-IOC-03 BL11I-EA-IOC-04
    IOCS += BL11I-MO-IOC-01 BL11I-MO-IOC-02 BL11I-MO-IOC-03 
    IOCS += BL11I-VA-IOC-01    
endif 

# These are the dirs that each IOC lives in
IOC_DIRS := $(patsubst %, $(TOP)/iocs/%, $(IOCS))
