# This file was automatically generated on Mon 05 Oct 2026 10:19:28 BST from
# source: /scratch/djp75990/code/I11/bl11i-builder/etc/makeIocs/BL11I-EA-IOC-12.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "/scratch/djp75990/code/I11/bl11i-builder/iocs/BL11I-EA-IOC-12"

epicsEnvSet "EPICS_CA_MAX_ARRAY_BYTES", '10000000'
epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------

cd "/scratch/djp75990/code/I11/bl11i-builder/iocs/BL11I-EA-IOC-12"

dbLoadDatabase "dbd/BL11I-EA-IOC-12.dbd"
BL11I_EA_IOC_12_registerRecordDeviceDriver(pdbbase)

drvAsynIPPortConfigure("ITC_CTLR", "10.111.8.7:7020", 100, 0, 0)

# Configure StreamDevice paths
epicsEnvSet "STREAM_PROTOCOL_PATH", "/dls_sw/prod/R3.14.12.7/support/OxInstCryojet/2-28/data"

# Final ioc initialisation
# ------------------------
cd "/scratch/djp75990/code/I11/bl11i-builder/iocs/BL11I-EA-IOC-12"
dbLoadRecords 'db/BL11I-EA-IOC-12_expanded.db'
iocInit
